### ISSUE TITLE
很小的但对我来说有点难理解的问题

### ISSUE THREAD

**Issue by IPNUISTlegal** [bojone/gan-qp#3]
苏大神，您好！
我是GAN的初学者。看到您的GAN-QP博客
(![image](https://user-images.githubusercontent.com/35527568/50040625-0750e000-0082-11e9-93ce-196bda052101.png))  与您代码中的d_loss = K.mean(- d_loss + 0.5 * d_loss**2 / d_norm) 刚好差个负号。不知道是什么原因。然后我查询了WGAN-GP，d_loss也是类似的情况，但是梯度惩罚（GP）是paper中一样加号就是加号。查询了最小二乘LSGAN的d的损失函数，代码跟paper表述一致。作为一个对GAN数学公式推导知之甚少的同学，希望能得到您的答复！谢谢

**Comment by bojone** [comment]
前面是argmax，加个负号变成argmin

**Comment by IPNUISTlegal** [comment]
1. ![image](https://user-images.githubusercontent.com/35527568/50369770-a2dbd680-05d5-11e9-9acd-7cb0b6554317.png)  我看了一下证明，判别器的目标函数是概率密度，概率密度和梯度不会消失和爆炸之间有什么关系？好像gan-qp并没有对梯度爆炸的来源做出一些解释
2. ![image](https://user-images.githubusercontent.com/35527568/50369821-4b8a3600-05d6-11e9-9549-03df6a998cca.png)  256x256的RGB图像算出λ是5e-5，您的代码给的是10，我知道λ是具有鲁棒性的。会不会像论文中所说这两个数字very large and very small？
谢谢苏大神(#^.^#)

**Comment by bojone** [comment]
1.散度，不是密度，详细讨论请看原论文；
2.(23)式跟代码的实现是一摸一样的，请认真看代码（K.mean，不是K.sum）。

**Comment by IPNUISTlegal** [comment]
好的，谢谢，第二个问题我懂了。
第一个问题，字打错了，想打概率散度结果打成概率密度^_^，毕竟我见到概率密度很多，很少见到概率散度。
概率散度和梯度不会消失和爆炸之间有什么关系？好像gan-qp并没有对梯度爆炸的来源做出一些解释

**Comment by bojone** [comment]
首先，论文的60%的篇幅都在谈梯度消失相关的；而剃度爆炸实际上跟梯度消失类似，如果你能看明白梯度消失的分析，梯度爆炸就不难理解了。

**Comment by IPNUISTlegal** [comment]
好的，谢谢苏大神。看来我还要很长的时间才能理解了
